#define Void 0
#define Integer 1
#define Boolean 2
#define Read 3
#define Write 4 
#define Initialize 5
#define Digit 6
#define Variable 7
#define Addition 8
#define Subtraction 9
#define Multiplacation 10
#define Division 11
#define And 12
#define Or 13
#define Not 14
#define Equal 15
#define NotEqual 16
#define LessThen 17
#define LessThenEqual 18
#define GreaterThen 19
#define GreaterThenEqual 20
#define True 21
#define False 22
#define Continue 23
#define Array 24
#define Decl 25
#define Remainder 26
#define Conditional 27
#define Iterative 28
#define ArrayInitialize 29
#define ArrayVariable 30
#define ArrayRead 31
#define Function 32
#define Main 33
#define Return 34
#define Argument 35
#define FunctionDecl 36
#define Expression 37
#define Parameter 38
#define RefInt 39
#define RefBool 40
